TheForgeWebsite/Main/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'Main'
urlpatterns = [
    path('', views.Index, name='index'),
    path('about/', views.About, name='about'),
    path('join/', views.Join, name='join'),
    path('contact/', views.Contact, name='contact'),
    path('ai/', views.AI, name='ai'),
    path('cyber/', views.Cyber, name='cyber'),
    path('iot/', views.IoT, name='iot'),
    path('charte/', views.Charte, name='charte'),
    path('faq/', views.FAQ, name='faq'),
    path('mentions/', views.Mentions, name='Mentions'),
    path('conditions/', views.Conditions, name='Conditions'),


    path('blog/', views.Blog, name='blog'),
    path('create_post/', views.Create_Post, name='create_post'),
    path('post/<int:pk>', views.Post_detail, name='post'),

    path('create_job/', views.Create_Job, name='create_job'),
    path('job/<int:pk>', views.Job_Detail, name='job'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TheForgeWebsite/TheForgeWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('Main.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TheForgeWebsite/Main/models.py
from django.db import models
from django.contrib.auth.models import User
from django_quill.fields import QuillField
import uuid

def get_image_filepath(instance, filename):
    ext = filename.split('.')[-1]
    filename = f"{uuid.uuid4()}.{ext}"
    return f'post_images/{instance.title}/{filename}'

def get_CV_filepath(instance, filename):
    ext = filename.split('.')[-1]
    filename = f"{uuid.uuid4()}.{ext}"
    return f'CV/{instance.job}/{filename}'

def get_Cover_letter_filepath(instance, filename):
    ext = filename.split('.')[-1]
    filename = f"{uuid.uuid4()}.{ext}"
    return f'CV/{instance.job}/{filename}'

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = QuillField()
    image = models.ImageField(upload_to=get_image_filepath, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']

class Job(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    location = models.CharField(max_length=100)
    type = models.CharField(max_length=50)  # Par exemple, plein temps, partiel, freelance
    posted_at = models.DateTimeField(auto_now_add=True)
    last_date_to_apply = models.DateField()

    def __str__(self):
        return f"{self.title}"

    class Meta:
        ordering = ['-posted_at']

class Applicant(models.Model):
    email = models.TextField(default='bdiouipierre@gmail.com')
    first_name = models.CharField(max_length=100, default="non renseigné")
    last_name = models.CharField(max_length=100, default="non renseigné")
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name='applicants')
    phone = models.TextField(default="non renseigné")
    cv = models.FileField(upload_to=get_CV_filepath, null=True, blank=True)
    cover_letter = models.FileField(upload_to=get_Cover_letter_filepath, null=True, blank=True)
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.job}"

class Message(models.Model):
    email = models.TextField()
    content = models.TextField()
    first_name = models.CharField(max_length=100, default="non renseigné")
    last_name = models.CharField(max_length=100, default="non renseigné")
    phone = models.TextField(default="non renseigné")
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email + ' : ' + self.submitted_at

class ContactRequest(models.Model):
    # Définir les champs selon le formulaire
    email = models.EmailField(max_length=255)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    field = models.CharField(max_length=100)
    content = models.TextField()
    phone = models.TextField(default="non renseigné")
    callback_request = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.company}"

TheForgeWebsite/Main/forms.py
from django import forms
from .models import Post, Job
from django_quill.forms import QuillFormField

class PostForm(forms.ModelForm):
    content = QuillFormField()
    class Meta:
        model = Post
        fields = ['title', 'content', 'image']

class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = '__all__'

TheForgeWebsite/Main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm, JobForm
from .models import *
from django.core.mail import EmailMessage
from django.template.loader import get_template
from django.conf import settings
from django.contrib import messages
import requests
import os

# Create your views here.
def Index(request):
    posts = Post.objects.all().order_by('-created_at')[:6]
    return render(request, 'Main/Index.html', {'posts':posts})
def Charte(request):
    return render(request, 'Main/Charte.html')

def Mentions(request):
    return render(request, 'Main/Mentions.html')

def Conditions(request):
    return render(request, 'Main/Conditions.html')

def FAQ(request):
    if request.method == "POST":
        recaptcha_response = request.POST.get('g-recaptcha-response')
        data = {
            'secret': settings.RECAPTCHA_PRIVATE_KEY,
            'response': recaptcha_response
        }
        r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
        result = r.json()

        if result['success']:
            callback_request = request.POST.get('callback_request') == 'on'

            # Mail de confirmation
            email_template = get_template(os.path.join(settings.BASE_DIR, 'Main/templates/Main/request_confirmation.html'))
            email = request.POST.get('email')
            subject = 'Demande reçue !'
            email_body = email_template.render()
            from_email = settings.EMAIL_HOST_USER
            recipient_list = [email]

            email = EmailMessage(subject, email_body, from_email, recipient_list)
            email.content_subtype = 'html'
            email.send()

            # email pour l'admin du site
            callback_request = request.POST.get('callback_request') == 'on'

            email = request.POST.get('email'),
            first_name = request.POST.get('first_name'),
            last_name = request.POST.get('last_name'),
            content = request.POST.get('content'),
            company = request.POST.get('company'),
            phone = request.POST.get('phone'),
            field = '-',
            callback_request = 'oui' if callback_request else 'non'

            context = {
                'first_name': request.POST.get('first_name'),
                'last_name': request.POST.get('last_name'),
                'email': request.POST.get('email'),
                'content': request.POST.get('content'),
                'phone': request.POST.get('phone'),
                'field': request.POST.get('field'),
                'company': request.POST.get('company'),
                'callback_request': callback_request,
            }

            # Mail de confirmation
            email_template = get_template(os.path.join(settings.BASE_DIR, 'Main/templates/Main/Admin_alert.html'))
            subject = 'Nouveau message'
            email_body = email_template.render(context)
            from_email = settings.EMAIL_HOST_USER
            recipient_list = ['adrien.schwartzentruber@theforge.fr']

            email = EmailMessage(subject, email_body, from_email, recipient_list)
            email.content_subtype = 'html'
            email.send()
            messages.success(request, 'Votre demande a bien été envoyée !')
            return redirect("Main:faq")
        else:
            messages.error(request, 'Oups ! Erreur de Captcha!')
            return redirect("Main:faq")
    else:
        return render(request, 'Main/FAQ.html')

def AI(request):
    if request.method == "POST":
        recaptcha_response = request.POST.get('g-recaptcha-response')
        data = {
            'secret': settings.RECAPTCHA_PRIVATE_KEY,
            'response': recaptcha_response
        }
        r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
        result = r.json()

        if result['success']:
            callback_request = request.POST.get('callback_request') == 'on'
            contact_request = ContactRequest(
                email=request.POST.get('email'),
                first_name = request.POST.get('first_name'),
                last_name = request.POST.get('last_name'),
                content = request.POST.get('content'),
                company = request.POST.get('company'),
                phone=request.POST.get('phone'),
                field = request.POST.get('field'),
                callback_request = callback_request,
            )
            contact_request.save()

            # Mail de confirmation
            email_template = get_template(os.path.join(settings.BASE_DIR, 'Main/templates/Main/request_confirmation.html'))
            email = request.POST.get('email')
            subject = 'Demande reçue !'
            email_body = email_template.render()
            from_email = settings.EMAIL_HOST_USER
            recipient_list = [email]

            email = EmailMessage(subject, email_body, from_email, recipient_list)
            email.content_subtype = 'html'
            email.send()

            # email pour l'admin du site
            email = request.POST.get('email'),
            first_name = request.POST.get('first_name'),
            last_name = request.POST.get('last_name'),
            content = request.POST.get('content'),
            company = request.POST.get('company'),
            phone = request.POST.get('phone'),
            field = request.POST.get('field'),
            callback_request = 'oui' if callback_request else 'non'

            context = {
                'first_name': request.POST.get('first_name'),
                'last_name': request.POST.get('last_name'),
                'email': request.POST.get('email'),
                'content': request.POST.get('content'),
                'phone': request.POST.get('phone'),
                'field': request.POST.get('field'),
                'company': request.POST.get('company'),
                'callback_request': callback_request,

            }

            # Mail de confirmation
            email_template = get_template(os.path.join(settings.BASE_DIR, 'Main/templates/Main/Admin_alert.html'))
            subject = 'Nouveau message'
            email_body = email_template.render(context)
            from_email = settings.EMAIL_HOST_USER
            recipient_list = ['adrien.schwartzentruber@theforge.fr']

            email = EmailMessage(subject, email_body, from_email, recipient_list)
            email.content_subtype = 'html'
            email.send()
            messages.success(request, 'Votre demande a bien été envoyée !')
            return redirect('Main:ai')
        else:
            messages.error(request, 'Oups ! Erreur de Captcha!')
            return redirect("Main:ai")
    else:
        return render(request, 'Main/AI.html')

def Cyber(request):
    if request.method == "POST":
        recaptcha_response = request.POST.get('g-recaptcha-response')
        data = {
            'secret': settings.RECAPTCHA_PRIVATE_KEY,
            'response': recaptcha_response
        }
        r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
        result = r.json()

        if result['success']:
            callback_request = request.POST.get('callback_request') == 'on'
            contact_request = ContactRequest(
                email=request.POST.get('email'),
                first_name=request.POST.get('first_name'),
                last_name=request.POST.get('last_name'),
                content=request.POST.get('content'),
                phone=request.POST.get('phone'),
                company=request.POST.get('company'),
                field=request.POST.get('field'),
                callback_request=callback_request,
            )
            contact_request.save()

            # Mail de confirmation
            email_template = get_template(os.path.join(settings.BASE_DIR, 'Main/templates/Main/request_confirmation.html'))
            email = request.POST.get('email')
            subject = 'Demande reçue !'
            email_body = email_template.render()
            from_email = settings.EMAIL_HOST_USER
            recipient_list = [email]

            email = EmailMessage(subject, email_body, from_email, recipient_list)
            email.content_subtype = 'html'
            email.send()

            # email pour l'admin du site
            email = request.POST.get('email'),
            first_name = request.POST.get('first_name'),
            last_name = request.POST.get('last_name'),
            content = request.POST.get('content'),
            company = request.POST.get('company'),
            phone = request.POST.get('phone'),
            field = request.POST.get('field'),
            callback_request = 'oui' if callback_request else 'non'

            context = {
                'first_name': request.POST.get('first_name'),
                'last_name': request.POST.get('last_name'),
                'email': request.POST.get('email'),
                'content': request.POST.get('content'),
                'phone': request.POST.get('phone'),
                'field': request.POST.get('field'),
                'company': request.POST.get('company'),
                'callback_request': callback_request,

            }

            # Mail de confirmation
            email_template = get_template(os.path.join(settings.BASE_DIR, 'Main/templates/Main/Admin_alert.html'))
            subject = 'Nouveau message'
            email_body = email_template.render(context)
            from_email = settings.EMAIL_HOST_USER
            recipient_list = ['adrien.schwartzentruber@theforge.fr']

            email = EmailMessage(subject, email_body, from_email, recipient_list)
            email.content_subtype = 'html'
            email.send()
            messages.success(request, 'Votre demande a bien été envoyée !')
            return redirect('Main:cyber')
        else:
            messages.error(request, 'Oups ! Erreur de Captcha !')
    else:

TheForgeWebsite/Main/templates/Main/Admin_applicant.html
<!DOCTYPE html>
<html>
<head></head>
<body style="background-color:#F5F6F1; color:black;">
  <div class="container" style="border-radius:15px; padding:2rem; margin-left:auto; margin-right:auto; margin-top:4rem; margin-bottom:4rem; display: flex; justify-content: center; align-items: center; height: 500px; width:50%; padding:70px; background-color:white;">
    <div style="text-align: center;">
      <div><a href="https://www.tech-forge.fr">
        <img width="150" src="https://studio-script.sgp1.cdn.digitaloceanspaces.com/studio-script-static/img/Principal_noir.png">
      </a></div>
      <div>
        <h3 style="font-size:40px; font-weight:900;"> Nouvelle candidature spontannée sur The Forge !</h3>
        <p style="font-size:20px; ">Une nouvelle candidature a été reçue : </p><br>
        <hr>
        <div style="text-align:left;">
          <p><strong>Nom : </strong>{{first_name}} {{last_name}}</p>
          <p><strong>Email : </strong>{{email}}</p>
          <p><strong>Tel : </strong>{{phone}}</p>
        </div>
         <hr>

      </div>
    </div>
  </div>
</body>
</html>

TheForgeWebsite/Main/templates/Main/Create_Job.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Balises pour référencement naturel -->
    <meta name="description" content="Une Équipe de développement informatique spécialisée dans l'intelligence artificielle. Offrant des solutions innovantes pour les défis technologiques de demain.">
    <meta name="keywords" content="développement informatique, intelligence artificielle, IA, solutions technologiques, innovation, Web3, Informatique">
    <meta name="author" content="Tech Forge">

    <!-- Balises Open Graph pour les réseaux sociaux (remplacez les valeurs par les vôtres) -->
    <meta property="og:title" content="Tech Forge">
    <meta property="og:description" content="Une Équipe de développement informatique spécialisée dans l'intelligence artificielle. Offrant des solutions innovantes pour les défis technologiques de demain.">
    <meta property="og:type" content="website">
    <meta property="og:url" content="www.tech-forge.fr">
    <meta property="og:image" content="https://studio-script.sgp1.cdn.digitaloceanspaces.com/studio-script-static/img/facebook-socialsizes_Open%20Graph.png">

    <!-- Balises Twitter Card pour Twitter (remplacez les valeurs par les vôtres) -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@votrecompte">
    <meta name="twitter:title" content="Nom de votre entreprise">
    <meta name="twitter:description" content="Entreprise de développement informatique de pointe spécialisée dans l'intelligence artificielle. Offrant des solutions innovantes pour les défis technologiques du futur.">
    <meta name="twitter:image" content="URL de l'image à afficher sur Twitter">

    <!-- Favicon -->
     <link rel="icon" href="{% static 'Logos/Icones/Icones_beige.png' %}" type="image/x-icon">

    <title>Tech Forge - Jobs</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="{% static 'css/join.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.typekit.net/eqx7rzk.css">

  </head>

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-74E6QKK31W"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-74E6QKK31W');
</script>

  <body style="background-color:#FFF0D6 !important; color: #015453 !important; font-family: 'articulat-cf' !important;">

  <header>
  <!-- Barre de navigation -->
  <div class="container">
    <nav class="navbar navbar-expand-lg fixed-top navbar-light" id="mainNavbar" style="background-color:#FFF0D6 !important; color:#015453 !important;">
      <div class="container">
      <a class="navbar-brand" href="{% url 'Main:index' %}">
        <img src="{% static 'Logos/Principal/Principal_vert.svg' %}" alt="Logo Tech Forge" width="150">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse m-auto" id="navbarNavDropdown">
        <ul class="navbar-nav m-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Main:index' %}">Accueil</a>
          </li>
          <!-- Menu déroulant pour les services -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Notre expertise
            </a>
            <ul class="dropdown-menu" style="background-color:#FFF0D6; border-style:none;">
              <li><a class="nav-link" href="{% url 'Main:ai' %}">Intelligence artificielle</a></li>
              <li><a class="nav-link" href="{% url 'Main:cyber' %}">Cybersécurité</a></li>
              <li><a class="nav-link" href="{% url 'Main:iot' %}">IOT et matériel embarqué</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Entreprise
            </a>
            <ul class="dropdown-menu" style="background-color:#FFF0D6; border-style:none;">
              <li><a class="nav-link" href="{% url 'Main:about' %}">À propos</a></li>
              <li><a class="nav-link" href="{% url 'Main:blog' %}">Blog</a></li>
              <li><a class="nav-link" href="{% url 'Main:faq' %}">FAQ</a></li>
              <li><a class="nav-link" href="{% url 'Main:charte' %}">Charte</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Main:join' %}">L'équipe</a>
          </li>
        </ul>
          <a type="button" class="btn btn-outline-vert contact-item" href="{% url 'Main:contact' %}">Nous contacter</a>
      </div>
    </div>
    </nav>
  </div>
</header>

  <!-- Section services -->
  <Main>
    <!-- Section Hero -->
    <section>
      <form method="POST" class="container HeroContainer text-vert m-auto">
        {% csrf_token %}
        <div class="row justify-content-between align-items-center">
          <div class="col-12 display-2">Ouvrir un nouveau poste</div>
          <div class="col-12 mt-4">
             <div class="mb-3">
                <label for="id_title" class="form-label">Intitulé du poste:</label>
                <input type="text" class="form-control" id="id_title" name="title" placeholder="Titre du poste">
              </div>
              <div class="mb-3">
                <label for="id_description" class="form-label">Description:</label>
                <textarea class="form-control" id="id_description" name="description" placeholder="Description du poste"></textarea>
              </div>
              <div class="mb-3">
                <label for="id_location" class="form-label">Localisation:</label>
                <input type="text" class="form-control" id="id_location" name="location" placeholder="Lieu">
              </div>
              <div class="mb-3">
                <label for="id_type" class="form-label">Type de poste:</label>
                <input type="text" class="form-control" id="id_type" name="type" placeholder="Type de contrat">
              </div>
              <div class="mb-3">
                <label for="id_last_date_to_apply" class="form-label">Deadline :</label>
                <input type="date" class="form-control" id="id_last_date_to_apply" name="last_date_to_apply">
              </div>
            <button type="submit" class="btn btn-outline-vert">Publier le poste</button>
          </div>
        </div>
      </form>

    </section>
    <!-- Section Hero -->

  </Main>

  <footer class="footer text-vert" style="margin-top:15rem; background-color:#FFF0D6;">
  <div class="container text-vert borderTop" style="margin-bottom:150px;">
    <div class="row m-auto text-vert" style="padding-top:50px; padding-bottom:50px;">
      <div class="col-md-3 mb-3 mb-md-0 text-vert">
        <a href="{% url 'Main:index' %}">
          <img src="{% static 'Logos/Principal/Principal_vert.svg' %}" alt="Logo" height="40">
        </a>
      </div>
      <div class="col-md-3 mb-3 mb-md-0 bleu">
        <h5>Notre expertise</h5>
        <ul class="list-unstyled">
          <li><a href="{% url 'Main:ai' %}" class="text-vert">Intelligence artificielle</a></li>
          <li><a href="{% url 'Main:cyber' %}" class="text-vert">Cybersécurité</a></li>
          <li><a href="{% url 'Main:iot' %}" class="text-vert">IOT</a></li>
        </ul>
      </div>
      <div class="col-md-3">
        <h5>Entreprise</h5>
        <ul class="list-unstyled">
          <li><a href="{% url 'Main:join' %}" class="text-vert">Nous rejoindre</a></li>
          <li><a href="{% url 'Main:blog' %}" class="text-vert">Blog</a></li>
          <li><a href="{% url 'Main:faq' %}" class="text-vert">FAQ</a></li>
          <li><a href="{% url 'Main:charte' %}" class="text-vert">Charte</a></li>
        </ul>
      </div>
      <div class="col-md-3">
        <h5>Nous contacter</h5>
        <ul class="list-unstyled">
          <li><a href="mailto:contact@tech-forge.fr" class="text-vert">contact@tech-forge.fr</a></li>
          <li><a href="https://www.linkedin.com/company/theforgefr/about/?viewAsMember=true" class="text-vert">LinkedIn</a></li>
        </ul>
      </div>
    </div>
    <div class="borderTop row pt-3 justify-content-around m-auto">
      <div class="col-12 align-items-end" style="text-align:right">
         <a href="{% url 'Main:Conditions' %}" class="text-vert unstyled" style="text-align:right; margin:0 !important; margin-bottom:0px !important;">Conditions générales d'utilisation</a><br>
        <a href="{% url 'Main:Mentions' %}" class="text-vert unstyled" style="text-align:right; margin:0 !important; margin-bottom:0px !important;">Mentions légales</a>
      </div>
    </div>
  </div>
    <div class='row' style="width: 100%; height: auto; margin-right: 0; margin-left: 0;">
      <div class="col-6 px-0">
          <img loading="lazy" src="{% static 'Assets/Motifs/horizontale/footer_vert.webp' %}" alt="grille d'illustration géometrique du footer" style="width: 100.4%; height:auto;">
      </div>
      <div class="col-6 px-0">
          <img loading="lazy" src="{% static 'Assets/Motifs/horizontale/footer_vert.webp' %}" alt="grille d'illustration géometrique du footer" style="width: 100%; height:auto;">
      </div>
    </div>
</footer>

    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

  </body>
</html>

TheForgeWebsite/Main/templates/Main/Job_confirmation_libre.html
<!DOCTYPE html>
<html>
<head></head>
<body style="background-color:#F5F6F1; color:black;">
  <div class="container" style="border-radius:15px; padding:2rem; margin-left:auto; margin-right:auto; margin-top:4rem; margin-bottom:4rem; display: flex; justify-content: center; align-items: center; height: 500px; width:50%; padding:70px; background-color:white;">
    <div style="text-align: center;">
      <div><a href="https://www.tech-forge.fr">
        <img width="150" src="https://studio-script.sgp1.cdn.digitaloceanspaces.com/studio-script-static/img/Principal_noir.png">
      </a></div>
      <div>
        <h4 style="font-size:40px; font-weight:900;">Merci pour votre candidature </h4>
        <p style="font-size:20px; ">Merci pour votre candidature. Nous étudions votre demande et revenons vers vous très prochainement. </p>
        <p style="font-size:20px;"> <strong>L'équipe Tech Forge</strong></p>
        <a style="color:black; font-weight:900" href="https://www.tech-forge.fr">www.tech-forge.fr</a>
      </div>
    </div>
  </div>
</body>
</html>

TheForgeWebsite/Main/templates/Main/job_confirmation.html
<!DOCTYPE html>
<html>
<head></head>
<body style="background-color:#F5F6F1; color:black;">
  <div class="container" style="border-radius:15px; padding:2rem; margin-left:auto; margin-right:auto; margin-top:4rem; margin-bottom:4rem; display: flex; justify-content: center; align-items: center; height: 500px; width:50%; padding:70px; background-color:white;">
    <div style="text-align: center;">
      <div><a href="https://www.tech-forge.fr">
        <img width="150" src="https://studio-script.sgp1.cdn.digitaloceanspaces.com/studio-script-static/img/Principal_noir.png">
      </a></div>
      <div>
        <h3 style="font-size:40px; font-weight:900;">Merci pour votre candidature !</h3>
        <p style="font-size:20px; ">Merci d’avoir postulé pour le poste de {{job_title}}. Nous avons bien reçu votre candidature et nous vous contacterons prochainement.</p>
        <p style="font-size:20px;"> <strong>L'équipe Tech Forge</strong></p>
        <a style="color:black; font-weight:900" href="https://www.tech-forge.fr">www.tech-forge.fr</a>
      </div>
    </div>
  </div>
</body>
</html>

TheForgeWebsite/Main/templates/Main/message_confirmation.html
<!DOCTYPE html>
<html>
<head></head>
<body style="background-color:#F5F6F1; color:black;">
  <div class="container" style="border-radius:15px; padding:2rem; margin-left:auto; margin-right:auto; margin-top:4rem; margin-bottom:4rem; display: flex; justify-content: center; align-items: center; height: 500px; width:50%; padding:70px; background-color:white;">
    <div style="text-align: center;">
      <div><a href="https://www.tech-forge.fr">
        <img width="150" src="https://studio-script.sgp1.cdn.digitaloceanspaces.com/studio-script-static/img/Principal.jpg">
      </a></div>
      <div>
        <h3 style="font-size:40px; font-weight:900;">Merci pour votre message !</h3>
        <p style="font-size:20px; ">Nous avons bien reçu votre demande et revenons vers vous très prochainement. </p>
        <p style="font-size:20px;"> <strong>L'équipe Tech Forge</strong></p>
        <a style="color:black; font-weight:900" href="https://www.tech-forge.fr">www.tech-forge.fr</a>
      </div>
    </div>
  </div>
</body>
</html>